POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username": "huynh.hoang",
    "password": "12345678x@X"
}
###
POST http://localhost:5000/api/auth/signup
Content-Type: application/json

{
    "username": "huynh.hoang",
    "password": "12345678x@X",
    "fullName": "huynh hoang",
    "email": "huynhhoang@gmail.com"
}

###
POST http://localhost:5000/api/collection/create
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imh1eW5oLmhvYW5nIiwiaWF0IjoxNjA1Nzc3MzQyLCJleHAiOjE2MDU4NjM3NDJ9.j-2XKWvGU2okCyDQIl9n3Diby2j1wIczKnGaDt-2dx4

{
    "title": "test",
    "user_id": "5faa16bc7f927f08689a9401"
}

###
GET  http://localhost:5000/api/collection/5faa16bc7f927f08689a9401
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imh1eW5oLmhvYW5nIiwiaWF0IjoxNjA1MDY0NzUxLCJleHAiOjE2MDUxNTExNTF9.64lxsvZ2983b_uQdWKGj9-R4fmZe0TUKtc1uzq4O07s

###
POST   http://localhost:5000/api/task/create
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imh1eW5oLmhvYW5nIiwiaWF0IjoxNjA1MDY0NzUxLCJleHAiOjE2MDUxNTExNTF9.64lxsvZ2983b_uQdWKGj9-R4fmZe0TUKtc1uzq4O07s

{
    "description": "hello 2",
    "collection_id": "5fab58658ca70a14ec599483"
}

###
GET    http://localhost:5000/api/collection/get-task?id=5fab58658ca70a14ec599483
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imh1eW5oLmhvYW5nIiwiaWF0IjoxNjA1MDY0NzUxLCJleHAiOjE2MDUxNTExNTF9.64lxsvZ2983b_uQdWKGj9-R4fmZe0TUKtc1uzq4O07s


###
DELETE   http://localhost:5000/api/collection/remove
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imh1eW5oLmhvYW5nIiwiaWF0IjoxNjA1MDY0NzUxLCJleHAiOjE2MDUxNTExNTF9.64lxsvZ2983b_uQdWKGj9-R4fmZe0TUKtc1uzq4O07s

{
    "id": "5faa3eacc2400b118fcdc3d0"
}

###
PUT http://localhost:5000/api/collection/5faa447f5590851359911a45/title/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imh1eW5oLmhvYW5nIiwiaWF0IjoxNjA1MDY0NzUxLCJleHAiOjE2MDUxNTExNTF9.64lxsvZ2983b_uQdWKGj9-R4fmZe0TUKtc1uzq4O07s

{
    "title": "allllll"
}


###
POST http://localhost:5000/api/auth/signup
Content-Type: application/json

{
    "username": "huynh.hoang",
    "password": "12345678x@X",
    "fullName": "huynh hoang",
    "email": "huynh.hoang@gmail.com"
}