version: '3.7'

services:
  node:
    container_name: node_server
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    command: npm run dev
    networks:
      - common
    environment:
      PORT: 5000
      MONGO_HOST: 'mongo'
      MONGO_PORT: 27017
      MONGO_DB: 'todo-app'
      NODE_ENV: 'development'
      SECRET_STRING: 'a8XjWoe1KO4qCzRxtFkhrw=='

  mongo:
    container_name: mongo
    image: mongo:3.6.21
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    networks:
      - common
networks:
  common: